#!/usr/bin/env bash
set -euo pipefail
cd /data/.openclaw/workspace
npx tsx scripts/runtime-tests/ensure-samples.ts
OPENCLAW_RUNTIME_REAL_AUDIO=1 \
OPENCLAW_RUNTIME_AUDIO_BACKEND=ffmpeg \
OPENCLAW_RUNTIME_AUDIO_INPUT_FORMAT=file \
OPENCLAW_RUNTIME_AUDIO_INPUT_FILE=${OPENCLAW_RUNTIME_SAMPLE_DIR:-/data/.openclaw/workspace/fixtures/runtime-audio}/sample-2-es.mp3 \
OPENCLAW_RUNTIME_REAL_STT=1 \
OPENCLAW_RUNTIME_STT_LANG=es \
OPENCLAW_RUNTIME_ECHO_BACKEND=1 \
OPENCLAW_RUNTIME_REAL_TTS=1 \
OPENCLAW_RUNTIME_REAL_PLAYBACK=1 \
OPENCLAW_RUNTIME_AUDIO_POST_END_WAIT_MS=${OPENCLAW_RUNTIME_AUDIO_POST_END_WAIT_MS:-8000} \
npm run start:headless
